# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    strategy:
      matrix:
        config:
          - os: ubuntu-20.04
            GOOS: linux
            artifactName: linux-with-glibc2.31-ubuntu20
            artifactPath: network-guard
          - os: ubuntu-22.04
            GOOS: linux
            artifactName: linux-with-glibc2.35-ubuntu22
            artifactPath: network-guard
          - os: ubuntu-24.04
            GOOS: linux
            artifactName: linux-with-glibc2.39-ubuntu24
            artifactPath: network-guard
          - os: ubuntu-latest
            GOOS: windows
            artifactName: windows
            artifactPath: network-guard.exe
    runs-on: ${{ matrix.config.os }}
    env:
      GOOS: ""
    steps:
    - uses: actions/checkout@v3
    - name: Install libpcap-dev
      run: sudo apt install -y libpcap-dev
    - name: Fetch mac vendor db
      run: wget "https://maclookup.app/downloads/json-database/get-db" -O src/mac-vendors-export.json
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.23.4
    - name: Build
      run: GOOS=${{ matrix.config.GOOS }} GOARCH=amd64 go build -v ./...
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.2
      with:
        name: ${{ matrix.config.artifactName }}
        path: ${{ matrix.config.artifactPath }}
